# Use an official OpenJDK runtime as a parent image
FROM eclipse-temurin:17-jdk-alpine AS builder
  
  # Set working directory inside the container
WORKDIR /service
  
  # Copy Maven/Gradle wrapper and project files
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src
  
  # Package the application (skip tests for faster build)
RUN ./mvnw clean package -DskipTests
  
  # ---- Run stage ----
FROM eclipse-temurin:17-jre-alpine

WORKDIR /service
  
  # Copy jar file from builder stage
COPY --from=builder /service/target/service-*.jar service.jar
  
  # Expose port (change if your service runs on another port)
EXPOSE 8080
  
  # Run the jar
ENTRYPOINT ["java","-jar","service.jar"]
